services:
  database:
    image: mariadb:latest
    container_name: music_db
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_USER: ${DB_USER}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./Backend/MusicBackend/MusicBackend
      dockerfile: Dockerfile
      target: dev
    container_name: music_api
    depends_on:
      database:
        condition: service_healthy  # Only starts when DB is ready
    environment:
      - ConnectionStrings__DefaultConnection=${CONNECTION_STRING}
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - SUPERUSER_NAME=${SUPERUSER_NAME}
      - SUPERUSER_PWD=${SUPERUSER_PWD}
    ports:
      - "${BACKEND_PORT}:8080"
    healthcheck:
          test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
          interval: 10s
          timeout: 5s
          retries: 10
          start_period: 10s
    command: dotnet watch run --project MusicBackend.csproj --urls http://0.0.0.0:8080
    develop:
      watch:
        - action: sync
          path: ./Backend/MusicBackend/MusicBackend
          target: /src
          ignore:
            - bin/
            - obj/

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
      args:
        - PUBLIC_API_BASE_URL=${PUBLIC_API_BASE_URL}
      target: dev
    container_name: music_ui
    depends_on:
      backend:
        condition: service_healthy # Only starts when API is ready
    ports:
      - "${FRONTEND_PORT}:5173"
    develop:
      watch:
        - action: sync
          path: ./Frontend
          target: /app
          ignore:
            - node_modules/

volumes:
  db_data: